### ISSUE TITLE
Problems with mpv 0.7

### ISSUE THREAD

**Issue by ids1024** [np1/mps-youtube#155]
When I run mps-youtube with the new version of mpv, the status bar at the bottom does not show up and when a song ends, mpsyt tries again, thinking it failed.

**Comment by neo1691** [comment]
This issue seems to be affectine me too. I am using mpv 0.7.2 and whenever I quit a video (using q or ctrl-c) the video will start playing again. Not just playlist but any video. Is this relevant to this issue?

**Comment by ids1024** [comment]
That is the same problem. It is fixed in pull request #161, at least on Unix. I don't know if the problem exists on Windows.

**Comment by neo1691** [comment]
Okay @ids1024 I installed mps-youtube-git package from the aur (https://aur.archlinux.org/packages/mps-youtube-git/) and I still have this issue, so I think that the aur package will build from the master branch and not from the develop branch. is #161 merged with master?

**Comment by ids1024** [comment]
@neo1691 It is not merged with either develop or master. You can use the mpv0.7fix branch.  To use it in the AUR package, add "#branch=mpv0.7fix" to the end of the source url in the PKGBUILD.

**Comment by neo1691** [comment]
@ids1024 Thanks a lot!

**Comment by np1** [comment]
The PR (#161) has been merged into `develop` branch now. Branch `mpv0.7fix` will be deleted.
Thanks again @ids1024 for the fix :+1:

**Comment by np1** [comment]
Resolved in v0.2.2
