### ISSUE TITLE
Unicode issue with subprocess with some youtube links

### ISSUE THREAD

**Issue by pclausen** [np1/mps-youtube#253]
Great project - working well on my raspberry Pi. Most youtube links play fine. :-)

Unfortunately, I ran into this small problem and even after looking into the code I am unsure about how to fix it.

Problemematic link https://www.youtube.com/watch?v=tfQskCFtjnE: 
```bash
$ mpsyt playurl https://www.youtube.com/watch?v=tfQskCFtjnE --debug

mpsyt version  : 0.2.3
   notes       : released 17 Feb 2015
pafy version   : 0.3.72
Python version : 2.7.3 (default, Mar 18 2014, 05:13:23)
[GCC 4.6.3]
Processor      :
Machine type   : armv6l
Architecture   : 32bit, ELF
Platform       : Linux-3.12.29+-armv6l-with-debian-7.8
sys.stdout.enc : ANSI_X3.4-1968
default enc    : ascii
Config dir     : /home/clausen/.config/mps-youtube
env:TERM       : xterm
env:SHELL      : /bin/bash
David Maxim Mici? - Bilo (Full EP)
Traceback (most recent call last):
  File "/usr/local/bin/mpsyt", line 9, in <module>
    load_entry_point('mps-youtube==0.2.3', 'console_scripts', 'mpsyt')()
  File "/usr/local/lib/python2.7/dist-packages/mps_youtube/main.py", line 4427, in main
    if matchfunction(k, v, userinput):
  File "/usr/local/lib/python2.7/dist-packages/mps_youtube/main.py", line 4325, in matchfunction
    func(*matches)
  File "/usr/local/lib/python2.7/dist-packages/mps_youtube/main.py", line 3876, in play_url
    play(override, "1", "_")
  File "/usr/local/lib/python2.7/dist-packages/mps_youtube/main.py", line 3128, in play
    play_range(songlist, shuffle, repeat, override)
  File "/usr/local/lib/python2.7/dist-packages/mps_youtube/main.py", line 3220, in play_range
    returncode = playsong(song, override=override)
  File "/usr/local/lib/python2.7/dist-packages/mps_youtube/main.py", line 1955, in playsong
    returncode = launch_player(song, songdata, cmd)
  File "/usr/local/lib/python2.7/dist-packages/mps_youtube/main.py", line 2033, in launch_player
    stderr=subprocess.STDOUT, bufsize=1)
  File "/usr/lib/python2.7/subprocess.py", line 679, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1259, in _execute_child
    raise child_exception
TypeError: execv() arg 2 must contain only strings
```
It seems to me that the issue is that a unicode string is given to subprocess.Popen call: 
```python
cmd[2] : u'David Maxim Mici\u0107 - Bilo (Full EP)'
```
adding something in launch_player like:
```python
cmd[2]=xenc(cmd[2])
```
fixes the problem but it does not seem to be a very clean solution. Furthermore, the 'p' variable in launch_player is not correctly initialized.

I am very new to python modules, so if someone can point me to how to test the dev version (already have a git-clone on my box), but I dont know how to run this version. 
```bash
$ python main.py             
Traceback (most recent call last):
  File "main.py", line 34, in <module>
    from . import terminalsize
ValueError: Attempted relative import in non-package
```
I'll be happy to help if someone point me in the right direction.

**Comment by bendem** [comment]
Could it be related to / duplicate of #237?

**Comment by pclausen** [comment]
Yeah, could well be. I just got the dev-version running (git clone this evening), and it fails somewhat more gracefully:
```bash
$ ./mpsyt playurl https://www.youtube.com/watch?v=tfQskCFtjnE
David Maxim Mici? - Bilo (Full EP)


Num  Title                                                               Time
 1   David Maxim Mici? - Bilo (Full EP)                                 28:21

    [<-] seek [->]       [9] volume [0]
    [DN] SEEK [UP]       [space] pause       [q] return

    David Maxim Mici? - Bilo (Full EP) [28:21]
Problem playing last item: 'ascii' codec can't encode character u'\u0107' in position 20: ordinal not in range(128)
```

**Comment by ids1024** [comment]
I think your solution is alright, but it should probably instead by written as `cmd = [xenc(i) for i in cmd]`.

**Comment by ids1024** [comment]
It looks like this is related to issue #59.

**Comment by ids1024** [comment]
I think this would be fixed by using python 3.

@np1 What do you think about abandoning support for python 2 in mpsyt (pafy is a library, so it should still have python 2 support)? As far as I am aware this will not cause comparability issues with any distros (as long as it is installed with pip3 on systems were python 2 is the default), and it would fix problems like this and remove the hacks in the code for supporting both versions.

**Comment by np1** [comment]
Yes that's fine with me.

**Comment by zgrimshell** [comment]
I think this is a good idea - Fedora is going (or already is) defaulting to python3 and Debian is in process of huge "assault" on porting everything to python3 and then removing python2 so this will affect all downstream distros (Ubuntu, Mint, elementary etc).

**Comment by lol768** [comment]
:+1: to switching to only Python3 for mps-youtube.

**Comment by JKatzwinkel** [comment]
Seems you all put a lot of thought in it. At first I got a bit nervous about this as I use Fedora and Debian as secondary distros, but if everyone is all for it, I guess I'm cool with it and go find a way to install Python 3.4 on Debian.

**Comment by zgrimshell** [comment]
@JKatzwinkel Debian Jessie already has python3.4 (https://packages.debian.org/stable/python/python3) and you get it by sudo apt install python3

**Comment by pclausen** [comment]
Just tested using python3 on raspbian. Other youtube videos seems to work well, but the mentioned link still has issues (I did a 'git pull' just now):

```
rasp1:~/pyprojects/mps_youtube3/mps_youtube/mps-youtube$ mpsyt playurl https://www.youtube.com/watch?v=tfQskCFtjnE --debug

mpsyt version  : 0.2.5-dev
   notes       : development version
pafy version   : 0.3.72
Python version : 3.2.3 (default, Mar  1 2013, 11:53:50)
[GCC 4.6.3]
Processor      :
Machine type   : armv6l
Architecture   : 32bit, ELF
Platform       : Linux-3.12.29+-armv6l-with-debian-7.8
sys.stdout.enc : ANSI_X3.4-1968
default enc    : utf-8
Config dir     : /home/clausen/.config/mps-youtube
env:TERM       : xterm
env:SHELL      : /bin/bash
David Maxim Mici? - Bilo (Full EP)
Traceback (most recent call last):
  File "/home/clausen/pyprojects/mps_youtube3/bin/mpsyt", line 9, in <module>
    load_entry_point('mps-youtube==0.2.3', 'console_scripts', 'mpsyt')()
  File "/home/clausen/pyprojects/mps_youtube3/mps_youtube/mps-youtube/mps_youtube/main.py", line 4735, in main
    if matchfunction(k, v, userinput):
  File "/home/clausen/pyprojects/mps_youtube3/mps_youtube/mps-youtube/mps_youtube/main.py", line 4631, in matchfunction
    func(*matches)
  File "/home/clausen/pyprojects/mps_youtube3/mps_youtube/mps-youtube/mps_youtube/main.py", line 4181, in play_url
    play(override, "1", "_")
  File "/home/clausen/pyprojects/mps_youtube3/mps_youtube/mps-youtube/mps_youtube/main.py", line 3418, in play
    play_range(songlist, shuffle, repeat, override)
  File "/home/clausen/pyprojects/mps_youtube3/mps_youtube/mps-youtube/mps_youtube/main.py", line 3509, in play_range
    set_window_title(song.title + " - mpsyt")
  File "/home/clausen/pyprojects/mps_youtube3/mps_youtube/mps-youtube/mps_youtube/main.py", line 156, in set_window_title
    sys.stdout.write('\x1b]2;' + title + '\x07')
UnicodeEncodeError: 'ascii' codec can't encode character '\u0107' in position 20: ordinal not in range(128)
```

**Comment by ids1024** [comment]
Should be fixed by 0b5be5d7604bad239ee802659fdaba2819c7a1ce.

**Comment by pclausen** [comment]
Just made a git pull and it seems the issue has changed, but link still does not play. Please try:
```
$ mpsyt playurl https://www.youtube.com/watch?v=tfQskCFtjnE --debug
```

My current error
```
$ mpsyt playurl https://www.youtube.com/watch?v=tfQskCFtjnE --debug

mpsyt version  : 0.2.5-dev
   notes       : development version
pafy version   : 0.3.72
Python version : 3.2.3 (default, Mar  1 2013, 11:53:50)
[GCC 4.6.3]
Processor      :
Machine type   : armv6l
Architecture   : 32bit, ELF
Platform       : Linux-3.12.29+-armv6l-with-debian-7.8
sys.stdout.enc : ANSI_X3.4-1968
default enc    : utf-8
Config dir     : /home/clausen/.config/mps-youtube
env:TERM       : xterm
env:SHELL      : /bin/bash
David Maxim Mici? - Bilo (Full EP)
Traceback (most recent call last):
  File "/usr/lib/python3.2/logging/__init__.py", line 941, in emit
    stream.write(msg)
UnicodeEncodeError: 'ascii' codec can't encode character '\u0107' in position 53: ordinal not in range(128)
Logged from file main.py, line 332
Traceback (most recent call last):
  File "/usr/lib/python3.2/logging/__init__.py", line 941, in emit
    stream.write(msg)
UnicodeEncodeError: 'ascii' codec can't encode character '\u0107' in position 40: ordinal not in range(128)
Logged from file main.py, line 2079
Traceback (most recent call last):
  File "/usr/lib/python3.2/logging/__init__.py", line 941, in emit
    stream.write(msg)
UnicodeEncodeError: 'ascii' codec can't encode character '\u0107' in position 50: ordinal not in range(128)
Logged from file main.py, line 2080
Traceback (most recent call last):
  File "/home/clausen/pyprojects/mps_youtube3/mps_youtube/mps-youtube/mps_youtube/main.py", line 2163, in launch_player
    stderr=subprocess.STDOUT, bufsize=1)
  File "/usr/lib/python3.2/subprocess.py", line 745, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.2/subprocess.py", line 1207, in _execute_child
    restore_signals, start_new_session, preexec_fn)
UnicodeEncodeError: 'ascii' codec can't encode character '\u0107' in position 16: ordinal not in range(128)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/clausen/pyprojects/mps_youtube3/bin/mpsyt", line 9, in <module>
    load_entry_point('mps-youtube==0.2.4', 'console_scripts', 'mpsyt')()
  File "/home/clausen/pyprojects/mps_youtube3/mps_youtube/mps-youtube/mps_youtube/main.py", line 4735, in main
    if matchfunction(k, v, userinput):
  File "/home/clausen/pyprojects/mps_youtube3/mps_youtube/mps-youtube/mps_youtube/main.py", line 4631, in matchfunction
    func(*matches)
  File "/home/clausen/pyprojects/mps_youtube3/mps_youtube/mps-youtube/mps_youtube/main.py", line 4181, in play_url
    play(override, "1", "_")
  File "/home/clausen/pyprojects/mps_youtube3/mps_youtube/mps-youtube/mps_youtube/main.py", line 3418, in play
    play_range(songlist, shuffle, repeat, override)
  File "/home/clausen/pyprojects/mps_youtube3/mps_youtube/mps-youtube/mps_youtube/main.py", line 3511, in play_range
    returncode = playsong(song, override=override)
  File "/home/clausen/pyprojects/mps_youtube3/mps_youtube/mps-youtube/mps_youtube/main.py", line 2081, in playsong
    returncode = launch_player(song, songdata, cmd)
  File "/home/clausen/pyprojects/mps_youtube3/mps_youtube/mps-youtube/mps_youtube/main.py", line 2222, in launch_player
    if p and p.poll() is None:
UnboundLocalError: local variable 'p' referenced before assignment
```

**Comment by ids1024** [comment]
Ok, I think that should be fixed by commit 0b5be5d7604bad239ee802659fdaba2819c7a1ce.
